config/routes.rb
Rails.application.routes.draw do
  get 'render/index'
  devise_for :users
  root to: 'pages#home'
  # root 'render#home'
  resources :services, only: [:index, :show]
  resources :orders, only: [:create, :show] do
    resources :payments, only: :new
  end

  mount StripeEvent::Engine, at: '/stripe-webhooks'

  resources :queries, only: :create

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get '/covid', to: 'pages#covid'
  get '/reviews', to: 'pages#reviews'
  get '/whatwedo', to: 'pages#whatwedo'
  get '/contact', to: 'pages#contact'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :service

  monetize :amount_cents
end

app/models/query.rb
class Query < ApplicationRecord

  validates :name, :email, :message, presence: true
  validates :name, format: { with: /[a-z ,.'-]+/i,
                             message: "only allows letters from the alphabet a-z and spaces"
                             }
  validates :email, format: { with: /\S+@\S+/ }
  validates :message, length: { minimum: 5,
                                 message: "Your message needs to be at least 15 characters long."
                              }



end

app/models/service.rb
class Service < ApplicationRecord

  monetize :price_cents

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  after_create :send_welcome_email

  has_many :orders

  ADDRESSES = []


  private

  def send_welcome_email
    UserMailer.welcome(self).deliver_now
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  include Pundit

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:firstname, :last_name, :house_name_or_number, :postal_code])

    # I left the option below commented out until it is needed.
    # For additional in app/views/devise/registrations/edit.html.erb
    # devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end


end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  def create
    service = Service.find(params[:service_id])
    order  = Order.create!(service: service, service_name: service.name, amount: service.price, state: 'pending', user: current_user)
    authorize order

    session = Stripe::Checkout::Session.create(
      payment_method_types: ['card'],
      line_items: [{
        name: service.name,
        images: [service.photo_url],
        amount: service.price_cents,
        currency: 'gbp',
        quantity: 1
      }],
      success_url: order_url(order),
      cancel_url: order_url(order)
    )

    order.update(checkout_session_id: session.id)
    redirect_to new_order_payment_path(order)
  end

  def show
    @order = current_user.orders.find(params[:id])
    authorize @order # not sure if this is correct?!?!
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home, :covid, :reviews, :whatwedo, :contact ]

  def home
    @services = Service.all
    @query = Query.new
  end

  def covid
  end

  def reviews
  end

  def whatwedo
  end

  def contact
  end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController

def new
    @order = current_user.orders.where(state: 'pending').find(params[:order_id])
    authorize @order
  end
end

app/controllers/queries_controller.rb
class QueriesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :create ]


  def create
    @query = Query.new(query_params)
    authorize @query
    if @query.save
      QueryMailer.creation_confirmation(@query).deliver_now
      QueryMailer.creation_notification(@query).deliver_now
      redirect_to root_path
    else
      flash[:danger] = @query.errors.full_messages.join(', ')
    end
  end




  def query_params
    params.require(:query).permit(:name, :email, :message)
  end


end

app/controllers/render_controller.rb
class RenderController < ApplicationController
  def home
  end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  skip_before_action :authenticate_user!

  def index
    @services = Service.all
  end

  def show
    @service = Service.find(params[:id])
    authorize @service
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        # Tell the UserMailer to send a welcome email after save
        @user.send_welcome_email

        format.html { redirect_to(@user, notice: 'User was successfully created.') }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pawlett</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <%= favicon_link_tag asset_path('favicon.png') %>
  </head>

  <body>
            <%#= render 'shared/navbar' %>
            <%= render 'shared/flashes' %>
            <%= yield %>
            <%#= render 'shared/footer' %>
  </body>
</html>

app/views/orders/show.html.erb
<div class="container">
  <div class="row py-4">
    <div class="col-md-3"><%= image_tag @order.service.photo_url, width: '100%' %></div>
    <div class="col">
      <h1>Order #<%= @order.id %> <small><span class="badge badge-primary"><%= @order.state %></span></small></h1>
      <ul class="list-unstyled">
        <li><strong>ISSUED ON</strong> <%= @order.created_at.to_date %></li>
        <li><strong>Service</strong> <%= @order.service.name %></li>
        <li><strong>TOTAL</strong> <%= humanized_money_with_symbol @order.amount %></li>
        </li>
      </ul>
      <p>Estimated delivery in <strong>2 business days</strong></p>
    </div>
  </div>
</div>

app/views/pages/contact.html.erb
<div class="container reviews">
  <%= render 'shared/navbar' %>
  <h1 class="text-uppercase">Contact Us</h1>
  <%= render 'shared/footer' %>
</div>

app/views/pages/covid.html.erb
<div class="article container">
  <%= render 'shared/navbar' %>
  <h1>Navigating through COVID-19</h1>
  <p class="headline">
    Pawlett Plumbing and Heating is committed to caring for the health and well-being of our partners and customers and playing a constructive role in supporting local health workers. No out of hours or call out charges for NHS or emergency service workers plus 20% off local rates.
  </p>
  <h2>Is Pawlett Plumbing and Heating taking Bookings?</h2>
  <p>
    In line with government guidance, we are continuing to provide essential and emergency maintenance, as long with time sensitive jobs in void properties that would cause disruption if not completed. We’re taking steps to minimise non-essential contact and using enhanced PPE.
  </p>
  <p>Throughout lock-down work we were undertaking works such as: Leaks, boiler breakdowns, blocked plumbing, no hot water, gas safety inspections, urgent upgrades, urgent repairs, legally required safety compliance such as gas safety inspections, washing machine repair.
  </p>
  <p>Examples of work we have resumed:
      Bathroom upgrades, cosmetic upgrades, replacement of currently fully operational systems, non urgent maintenance, projects in occupied homes, new bathrooms new en suites, plumbing for projects that do not currently need to commence.
  </p>
  <h2>What you need to do</h2>

  <p>Our engineers can still help you if you have an emergency.
    <strong>You must let us know if you (or your tenants) think you/they could be at risk of Covid-19 or are self-isolating</strong>
    so we can take proper safety precautions to protect both you and our engineers.
  </p>


  <h2>Cancellations</h2>

  <p>We’re operating a policy of no late cancellation fees for Covid related issues.
    <br>
    You will be able to re book later.
  </p>

  <h2>Booking a new job</h2>

  <p>When you book an emergency engineer appointment we’ll ask you if:</p>

  <ul>
    <li>
      <p>You or anyone in your/the home has been diagnosed with coronavirus.</p>
    </li>
    <li>
      <p>You or anyone else in your/the home is self-isolating</p>
    </li>
    <li>
      <p>Anyone in your/the home is at higher risk – i.e. over 70, respiratory disease, diabetes etc.</p>
    </li>
    <li>
      <p>Do you think you might have coronavirus? Do any tenants/other residents think they may have coronavirus.</p>
    </li>
  </ul>

  <p>If you answer ‘yes’ to any of these questions then we will assess your need for an engineer visit and additional precautions that might be possible</p>

  <p>
    <strong>If your circumstances change between a booking and a job you must contact us.</strong> Our engineer may also call you on the day of your appointment and ask the same set of questions, in case anything has changed since you booked.
  </p>

  <p>When an engineer does visit a customer’s home, they’ll take additional precautions – including hand-washing – before, during and after the appointment. They’ll protect you and your family members by keeping a safe distance at all times – and we ask you to do the same.</p>


  <h2>Protection from spreading the virus.</h2>
  <ul>
    <li>Our engineers began social distancing as a company policy before the government introduced mandatory measures.</li>
    <li>Our engineers are following government guidance and above and beyond this we are wearing enhancing PPE.</li>
    <li>No non essential operatives in operation (e.g. no apprentices on site no revisits by estimator, communications by estimator and staff via phone).</li>
    <li>Please open windows and if appropriate the back doors in increase ventilation. If working form home please where possible work in a different room from our operatives.</li>
  </ul>

  <h2>Our staff are second tier key workers</h2>

  <p id="lastp"> On Friday, 20th March, the UK Government defined a list of key workers whose efforts will be essential as the UK responds to the ongoing coronavirus outbreak. This list included utilities workers.
  </p>
  <%= render 'shared/footer' %>
</div>

app/views/pages/home.html.erb
<div class="container px-0">
  <%= render 'shared/navbar' %>
  <div class="carousel-section">
    <div id="carouselExampleFade" class="carousel slide carousel-fade" data-ride="carousel">
      <div class="carousel-inner">
        <div class="carousel-item active">
          <div class="carousel-img-background">
            <img src="/images/van2.jpeg" class="d-block filter-me" alt="...">
            <div class="blurb">
              <h1>Welcome to Pawlett Plumbing & Heating</h1>
              <a href="/#contact-form-tag" class="button">Book a Visit</a>
            </div>
          </div>
        </div>
        <div class="carousel-item">
          <div class="carousel-img-background">
            <img src="/images/Chris.jpeg" class="d-block filter-me" alt="...">
            <div class="blurb">
              <p class="likeH1">Welcome to Pawlett Plumbing & Heating</p>
              <a href="/#contact-form-tag" class="button">Book a Visit</a>
            </div>
          </div>
        </div>
        <div class="carousel-item">
          <div class="carousel-img-background">
            <img src="/images/Boiler.jpeg" class="d-block filter-me" alt="...">
            <div class="blurb">
              <p class="likeH1">Welcome to Pawlett Plumbing & Heating</p>
              <a href="/#contact-form-tag" class="button">Book a Visit</a>
            </div>
          </div>
        </div>
        <!-- I have commented out the following carousel-item because of an error in production mode -->
<!--         <div class="carousel-item">
          <div class="carousel-img-background">
            <img src="/images/Boiler_installation.jpeg" class="d-block filter-me" alt="...">
            <div class="blurb">
              <h1>Your trusted local plumbing service</h1>
              <button>Book a Visit</button>
            </div>
          </div>
        </div> -->
        <div class="carousel-item">
          <div class="carousel-img-background">
            <img src="/images/Bathroom.jpeg" class="d-block filter-me" alt="...">
            <div class="blurb">
              <p class="likeH1">Welcome to Pawlett Plumbing & Heating</p>
              <a href="/contact" class="button">Book a Visit</a>
            </div>
          </div>
        </div>
      </div>
      <a class="carousel-control-prev" href="#carouselExampleFade" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="carousel-control-next" href="#carouselExampleFade" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
    </div>
  </div>
  <div class="whyus-section text-center mt-5">
    <h2>Why Choose Us?</h2>
    <div class="why-us-cards d-flex mt-4 container">
      <div class="row d-flex justify-content-center mx-0">
        <div class="col-10 col-md-7 col-lg-4">
          <div class="why-us-card">
            <img src="/images/local.webp" alt="">
            <h3>Your local company</h3>
            <p>Established in 2016, Pawlett Plumbing & Heating Ltd are a local family-run business operating throughout Aberdeenshire and surrounding areas. We pride ourselves on offering our customers a high quality, friendly and reliable service.</p>
          </div>
        </div>
        <div class="col-10 col-md-7 col-lg-4">
          <div class="why-us-card">
            <img src="/images/rates.webp" alt="">
            <h3>Fair and Local Rates</h3>
            <p>We charge local rates to North East of Scotland. Fair and transparent pricing, ask for a detailed fixed-price quotation today.</p>
          </div>
        </div>
        <div class="col-10 col-md-7 col-lg-4">
          <div class="why-us-card">
            <img src="/images/experts.webp" alt="">
            <h3>Experts</h3>
            <p>With over 12 years experience in the field all engineers at PPH are  fully qualified and insured Gas Safe registered engineers. All of our workforce are trained through a 4 year modern apprenticeship programme giving us the skills to install and maintain hot and cold water <span id="Services-locator"></span>, gas central heating, drainage and weathering systems in all commercial, industrial and residential buildings.</p>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="services-section text-center mt-5">
    <h2 id="Services">Our Services</h2>
    <div class="service-cards d-flex mt-4 container">
      <div class="row d-flex justify-content-center">
        <div class="col-10 col-md-7 col-lg-4">
          <div class="service-card">
            <img src="/images/plumbing.webp" alt="">
            <h3>Plumbing</h3>
            <ul class="list-group mt-5">
              <li class="list-group-item">Emergency plumbing repairs</li>
              <li class="list-group-item">Vented & Unvented hot water systems</li>
              <li class="list-group-item">Leak trace and repair </li>
              <li class="list-group-item">General domestic and commercial plumbing maintenance </li>
              <li class="list-group-item">Outside tap installations and repair.</li>
              <li class="list-group-item">Drainage</li>
            </ul>
          </div>
        </div>
        <div class="col-10 col-md-7 col-lg-4">
          <div class="service-card">
            <img src="/images/boilers.webp" alt="">
            <h3>Boilers, Central Heating & Gas Services</h3>
            <ul class="list-group">
              <li class="list-group-item"> Gas boiler annual servicing</li>
              <li class="list-group-item">Central heating boiler installation and repair</li>
              <li class="list-group-item">Landlords gas safety inspections and certification</li>
              <li class="list-group-item">Underfloor heating </li>
              <li class="list-group-item">Radiator replacement </li>
              <li class="list-group-item">Central heating power flushes</li>
            </ul>
          </div>
        </div>
        <div class="col-10 col-md-7 col-lg-4">
          <div class="service-card">
            <img src="/images/bathroom2.png" alt="" id="bathroom-img">
            <h3>Bathrooms</h3>
            <p class="mt-5" id="bathrooms-description">We provide a bespoke bathroom design and installation service. We project manage the job working alongside local quality subcontractors. All of the Plumbing, Joinery, Tiling, Plastering, Electrical and Decoration works needed are taken care of so you don’t have to source individual tradesmen yourself. </p>
          </div>
        </div>
        <a href="/">Learn more about our services</a>
      </div>
    </div>
  </div>
  <div class="aboutus-section text-center container">
    <h2 id="AboutUs">About Us</h2>
    <div class="row d-flex justify-content-center">
      <div class="col-8 col-lg-3">
        <img src="/images/Ben.png" alt="">
        <h3>Ben Pawlett</h3>
        <p><em>Founder and Director</em></p>
      </div>
      <div class="col-10 col-lg-9 aboutus">
        <p>Established in 2016, Pawlett Plumbing & Heating Ltd are a local family-run business operating throughout Aberdeenshire and surrounding areas. We pride ourselves on offering our customers a high quality, friendly and reliable service.
As an approved member of the Gas Safe Organisation we aim to provide the highest standard of professional workmanship and expertise for all domestic and commercial plumbing and heating requirements with a 24-hour emergency call out service also in place.
If you have any Plumbing and Heating related requirements or queries, please don’t hesitate to get in contact with us.</p>
      </div>
    </div>
  </div>
  <div class="testimonials-section container">
    <h2 class="text-center">What Our Customers Say</h2>
    <div class="row d-flex justify-content-center">
      <div class="col-lg-5">
        <blockquote class="blockquote px-5">
          <i class="fas fa-quote-left"></i>
          <p class="mb-0">Fabulous service from this company. Will definitely be using and recommending them in future. Ben got straight back to me when I contacted him about an issue with our heating system. He arrived when he said he would, sorted the problem and was very thorough in checking everything was working as it should before he left.</p>
          <footer class="blockquote-footer">Joanne Taylor <cite title="Source Title"></cite></footer>
        </blockquote>
      </div>
      <div class="col-lg-5">
        <blockquote class="blockquote px-5">
          <i class="fas fa-quote-left"></i>
          <p class="mb-0">Great to have met Ben and his colleague Chris who have worked so diligently this last week. I cannot praise them enough and can really recommend them in all ways- very polite <span id="Contact-tag"></span> , tidy , punctual and dependable.</p>
          <footer class="blockquote-footer">   Hazel Bannerman<cite title="Source Title"></cite></footer>
        </blockquote>
      </div>
    </div>
    <a href="/reviews" class="text-center d-block">See more customer testimonials</a>
  </div>
  <div class="contact-section">
    <%= render 'specialist/contact' %>
  </div>
  <div class="footer-section">
    <%= render 'shared/footer' %>
  </div>
      </div>
    </div>
  </div>
</div>





<!-- <div class="pawlett-carousel-wrapper">
   <div class="container-fluid px-0 d-flex justify-content-center">
    <div id="carouselExampleIndicators" class="carousel slide pawlett-carousel" data-ride="carousel">
      <ol class="carousel-indicators">
        <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="3"></li>
      </ol>
      <div class="carousel-inner pawlett-carousel-inner">
        <div class="carousel-item active">
          <img class="d-block" src="/images/happy_customers_banner.jpg" alt="First slide">
          <div class="carousel-caption pawlett-carousel-caption">
            <h5>A warm welcome everytime</h5>
            <p>You won't find a friendlier plumber in the shire</p>
          </div>
        </div>
        <div class="carousel-item">
          <img class="d-block" src="/images/let_us_run_it.jpg" alt="Second slide">
          <div class="carousel-caption pawlett-carousel-caption">
            <h5>Let us run it</h5>
            <p>we can manage your new bathroom installatio from concept to completion</p>
          </div>
        </div>
        <div class="carousel-item">
          <img class="d-block" src="/images/radiator_banner.jpg" alt="Third slide">
          <div class="carousel-caption pawlett-carousel-caption">
            <h5>Keeping you warm in style</h5>
            <p>Specialists in all types of radiator installation.</p>
          </div>
        </div>
        <div class="carousel-item">
          <img class="d-block" src="/images/safe_as_houses.jpg" alt="Third slide">
          <div class="carousel-caption pawlett-carousel-caption">
            <h5>Safe as houses</h5>
            <p>Peace of mind for landlords, tenants and homeowners with our gas safety certificate service.</p>          </div>
          </div>
      </div>
      <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
    </div>
  </div>
</div> -->
<%#= render 'specialist/brands' %>
<%#= render 'specialist/services' %>
<%#= render 'specialist/contact' %>

app/views/pages/whatwedo.html.erb
<div class="article container">
  <%= render 'shared/navbar' %>
  <h1>Our Services</h1>
  <p class="headline">Pawlett Plumbing and Heating provide a full mechanical service to our clients. That means all plumbing, heating, gas, electrical and appliance maintenance work is undertaken as well as design installations.

By operating on local bases we can provide a professional service with highly competitive prices. We don't have the logistical problems that larger companies, as well as many independents, suffer from covering an area as big as Aberdeenshire or more. </p>

  <p>We provide prompt, clear, competitive and free quotes.</p>
  <p>Ben is a highly qualified experience plumber, heating, gas engineer, and appliance tester, with experience in inspections and design for local authority housing and property maintenance and development companies.</p>

  <ul>
    <li></li>
  </ul>


<li>New installations; design and build.<li>

<li>Renovations, new plumbing and heating systems, plumbing for new and refurbished bathrooms and kitchens.<li>

<li>Installations of showers and shower mixers.<li>

<li>Leaks; repairs and tracing.<li>

<li>Plumbing fault finding and diagnostics; shower flow issues, drainage issues, supply problems.<li>

<li>General repairs to taps valves and other components.<li>

<li>Hot water issues; too hot or cold, temperate drops. Intermittent flow issues. Lack of supply.<li>

<li>Plumbing for power showers and pumped showers. (A bristan certified shower specialist.)<li>

<li>Design for plumbing systems with pipe sizing.<li>

<li>Water hammer issues, and noisy systems.<li>

<li>Flow problems, lack of water, intermittent flow.<li>

<li>Shared mains issues.<li>

<li>Unvented cylinders installation (megaflows etc).<li>

<li>Changing taps and valve.<li>

<li>Stop cock, stop valve installation repairs and swaps.<li>
<li>Pipe freezing.</li>
<li>Whale shower pumps, installation & Repairs<li>




























  <%= render 'shared/footer' %>
</div>

app/views/payments/new.html.erb
<%= render 'shared/orderprocess' %>



<div class="container">
  <div class="row py-4">
    <div class="col-md-3"><%= image_tag @order.service.photo_url, width: '100%' %></div>
    <div class="col">
      <h1>Time & Date</h1>
      <p>Purchase of <strong><%= @order.service.name %></strong> for <strong><%= humanized_money_with_symbol @order.amount %></strong></p>
      <button id="pay" class="btn btn-primary">Pay</button>
      <script src="https://js.stripe.com/v3/"></script>
      <script>
        const paymentButton = document.getElementById('pay');
        paymentButton.addEventListener('click', () => {
          const stripe = Stripe('<%= ENV['STRIPE_PUBLISHABLE_KEY'] %>');
          stripe.redirectToCheckout({
            sessionId: '<%= @order.checkout_session_id %>'
          });
        });
      </script>
    </div>
  </div>
</div>

app/views/render/home.html.erb
<main class="container">
  <div class="row text-center justify-content-center">
    <div class="col">
      <h1 class="display-4">Hello World!</h1>
    </div>
  </div>
</main>

app/views/services/index.html.erb
<h1>Page showing all the services</h1>

<div class="container">
  <div class="row">
    <% @services.each do |service|%>
      <div class="col-6 col-md-4">
        <div class="card">
          <%= image_tag service.photo_url , class: "card-img-top" %>
          <div class="card-body">
            <h5 class="card-title"><%= service.name %></h5>
            <p>Amount: <%= humanized_money_with_symbol(service.price) %></p>
            <%= link_to "More details", service_path(service), class: "btn btn-primary" %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/services/show.html.erb
<%= render 'shared/orderprocess' %>

<div class="container service-description-box mt-5">
  <div class="">
    <div><h1 class="text-center mt-4 mb-3">Annual Boiler Service</h1></div>
    <div class="d-flex justify-content-center"><%= image_tag(@service.photo_url, width: '50%', :class => "rounded") %></div>
    <div><h2 class="mt-5">What's included?</h2></div>
    <div class="mb-5">
      <ul>
        <li>we'll visit you at the time agreed</li>
        <li>we'll visit you at the time agreed</li>
        <li>we'll visit you at the time agreed</li>
        <li>we'll visit you at the time agreed</li>
        <li>we'll visit you at the time agreed</li>
      </ul>
    </div>
    <div class="d-flex justify-content-center"><p class="price"><%= humanized_money_with_symbol(@service.price) %></p></div>
  </div>

</div>
<div class="container service-buttons-box mt-3 mb-5">
  <div class="d-flex justify-content-center">
    <%= link_to 'Back', root_path, :class => "mr-4 button-back" %>
    <%= form_tag orders_path do %>
          <%= hidden_field_tag 'service_id', @service.id %>
          <%= submit_tag 'Book', class: 'mr-4 button-forward' %>
      <% end %>
  </div>
</div>

app/views/specialist/_services.html.erb
<div class="d-flex justify-content-center services-group-wrapper ">
  <div class="services-group">
    <div class="container-fluid d-flex justify-content-center pt-5 pb-5">
      <div class="book-services-registration d-flex justify-content-between align-items-center">
        <h1>Book services online</h1>
        <div class="registration-form">
          <%= link_to "Register", new_user_registration_path, :class => "btn-dark-register mb-2" %>
        </div>
      </div>
    </div>
    <div class="book-services-online">
      <div class="container d-flex justify-content-center">
        <div class="row" style="width: 1100px">
          <% @services.each do |service| %>
            <% if service.bookable == true %>
              <div class="col-6 d-flex justify-content-center">
                <div class="card" style="width: 25rem;">
                  <%= image_tag service.photo_url, alt: "Card image cap", width: 380, height: 240, :class => "card-img-top" %>
                  <!-- <img class="card-img-top" src="..." alt="Card image cap"> -->
                  <div class="card-body">
                    <h5 class="card-title"><%= service.name %></h5>
                    <p class="card-text"><%= service.description %></p>
                    <%= link_to 'click here', service_path(service) %>
                    <!-- <a href="#" class="btn btn-primary">Go somewhere</a> -->
                  </div>
                </div>
              </div>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
    <hr>
    <div class="container-fluid d-flex justify-content-center pt-2 pb-5">
      <div class="services-byarrangement">
        <h1>Contact us for other services</h1>
      </div>
    </div>
    <div class="book-services-online">
      <div class="container d-flex justify-content-center">
        <div class="row" style="width: 1100px">
          <% @services.each do |service| %>
            <% if service.bookable == false %>
              <div class="col-6">
                <div class="card mb-5" style="width: 25rem;">
                  <%= image_tag service.photo_url, alt: "Card image cap", width: 380, height: 240, :class => "card-img-top" %>
                  <!-- <img class="card-img-top" src="..." alt="Card image cap"> -->
                  <div class="card-body">
                    <h5 class="card-title"><%= service.name %></h5>
                    <p class="card-text"><%= service.description %></p>
                    <!-- <a href="#" class="btn btn-primary">Go somewhere</a> -->
                  </div>
                </div>
              </div>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>



















  </div>
</div>